version: "3"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iplab_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - iplab_postgres
    restart: always

  iplab_postgres:
    image: postgres:16.1
    container_name: iplab_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - iplab_postgres_data:/var/lib/postgresql/data

volumes:
  iplab_postgres_data: